# Custom Language File for Launcher Customizer

[ejs.app]
title = "Surge"

[ejs.landing]
mediaGitHubURL = "https://github.com/MineSurgeRepo/SurgeLauncher"
mediaTwitterURL = ""
mediaInstagramURL = ""
mediaYouTubeURL = ""
mediaDiscordURL = "https://discord.gg/MineSurge"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/SurgeLauncher"
supportLink = "https://github.com/dscalZi/SurgeLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO MINESURGE"
welcomeDescription = "The long-awaited merger between Lifesteal and HCF has finally arrived. Experience joy like no other with MineSurge." 
welcomeDescCTA = "Your adventure awaits you today."
